### ISSUE TITLE
[Proposal] Move overrides files into sub-folder allowing for git-submodules

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-theme#3]
I was wondering if you would be open to the idea of moving the `overrides.css` file into a sub-directory that a user could choose to setup as a git-submodule.  This would allow a user, such as myself, to keep a separate git repo in my own sub-module and keep those changes separate from your `quest-child` repo.

I started writing some changes to `functions.php` and realized I'd rather keep those changes in another file altogether rather than confuse the commit history (and future pulls from your repo) ... I was going to submit a pull request to allow a `overrides.php` file to be included as well much to this same end ... but I wanted to check with you first about this line of thinking.  

How do you feel about moving all the `overrides` into a sub-folder?

```
overrides/styles.css
overrides/functions.php
```

I think it could help keep things clean and allow myself (and maybe others) to track their own separate development away from your own base child theme.  If you are up for this, I can submit the pull requests.

**Comment by elizoller** [comment]
Sounds good.

**Comment by thornomad** [comment]
Maybe we can also put some logic in there so someone can override a template that `quest-child` already overrides ... for example, the `footer.php` file ... so if a `footer.php` file exists at:

```
overrides/footer.php
```

It would use that one first.  Thoughts?

**Comment by elizoller** [comment]
instead of the one at `quest-child/footer.php` ? That makes sense

**Comment by thornomad** [comment]
Yea ... since that plugin is so tightly coupled with the child theme ... am thinking of how we can make the child theme a little more customizable ... a git submodule came to mind ... or like a "grandchild" theme ... however, a google search for that would imply the developers did not intend for that behavior.

I'll look into it a little more.

**Comment by elizoller** [comment]
Yeah I've looked up the concept of a "grandchild" theme before and not had much success. Is the git submodule worth pursuing?

**Comment by thornomad** [comment]
Am wondering that ... Let me look at it again soon ... I think it may still
be useful for people (myself) who only want a style.css and functions.php
override ... Even if I was only going that route I would want to keep those
files in a git repo so I can track changes and push them to the
local/production/live servers ... So I think there is still value in that.

But maybe grander plans for managing other template overrides are not so
feasible.

Long weekend started today! Have a good one. More later.
